-- MySQL Script generated by MySQL Workbench
-- Sat Oct 13 18:32:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`people` (
  `account_number` VARCHAR(16) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `name` CHAR(45) NOT NULL,
  `sex` ENUM('male', 'female') NOT NULL,
  `age` INT NOT NULL,
  `phone_number` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`account_number`),
  UNIQUE INDEX `account_number_UNIQUE` (`account_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier` (
  `people_account_number` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`people_account_number`),
  INDEX `fk_supplier_people1_idx` (`people_account_number` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_people1`
    FOREIGN KEY (`people_account_number`)
    REFERENCES `mydb`.`people` (`account_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `name` VARCHAR(45) NOT NULL,
  `supplier_people_account_number` VARCHAR(16) NOT NULL,
  `production_date` DATETIME NOT NULL,
  `expiration_date` DATETIME NOT NULL,
  `unit_price` INT NOT NULL,
  `discount` FLOAT NOT NULL,
  `stock_quantity` INT NOT NULL,
  `type` ENUM('clothing', 'food', 'fun') NULL,
  PRIMARY KEY (`name`, `supplier_people_account_number`),
  INDEX `fk_product_supplier1_idx` (`supplier_people_account_number` ASC) VISIBLE,
  CONSTRAINT `fk_product_supplier1`
    FOREIGN KEY (`supplier_people_account_number`)
    REFERENCES `mydb`.`supplier` (`people_account_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vip` (
  `points` INT NOT NULL,
  `discount_rate` FLOAT NULL,
  PRIMARY KEY (`points`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `people_account_number` VARCHAR(16) NOT NULL,
  `vip_points` INT NOT NULL,
  PRIMARY KEY (`people_account_number`),
  INDEX `fk_customer_vip1_idx` (`vip_points` ASC) VISIBLE,
  CONSTRAINT `fk_customer_people1`
    FOREIGN KEY (`people_account_number`)
    REFERENCES `mydb`.`people` (`account_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_vip1`
    FOREIGN KEY (`vip_points`)
    REFERENCES `mydb`.`vip` (`points`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_form` (
  `order_id` INT NOT NULL,
  `customer_people_account_number` VARCHAR(16) NOT NULL,
  `supplier_people_account_number` VARCHAR(16) NOT NULL,
  `money` FLOAT NOT NULL,
  `phone_number` VARCHAR(8) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `order_time` DATETIME NOT NULL,
  `delivery_time` DATETIME NOT NULL,
  `status` ENUM('suspending', 'delivered', 'solved', 'returned') NOT NULL,
  `return_reason` VARCHAR(200) NULL,
  INDEX `fk_order_form_customer1_idx` (`customer_people_account_number` ASC) VISIBLE,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_form_supplier1_idx` (`supplier_people_account_number` ASC) VISIBLE,
  CONSTRAINT `fk_order_form_customer1`
    FOREIGN KEY (`customer_people_account_number`)
    REFERENCES `mydb`.`customer` (`people_account_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_form_supplier1`
    FOREIGN KEY (`supplier_people_account_number`)
    REFERENCES `mydb`.`supplier` (`people_account_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `order_form_order_id` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `amount` INT NULL,
  PRIMARY KEY (`product_name`, `order_form_order_id`),
  INDEX `fk_order_product1_idx` (`product_name` ASC) VISIBLE,
  CONSTRAINT `fk_order_order_form1`
    FOREIGN KEY (`order_form_order_id`)
    REFERENCES `mydb`.`order_form` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_product1`
    FOREIGN KEY (`product_name`)
    REFERENCES `mydb`.`product` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `order_form_order_id` INT NOT NULL,
  `comment` VARCHAR(200) NOT NULL,
  `time` DATETIME NOT NULL,
  `value` FLOAT NOT NULL,
  INDEX `fk_comment_order_form1_idx` (`order_form_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_order_form1`
    FOREIGN KEY (`order_form_order_id`)
    REFERENCES `mydb`.`order_form` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
